hydra:
  run:
    dir: ${save_dir}
  job:
    name: ${job_name}

project_root: ${oc.env:PROJECT_ROOT}
save_dir: ${oc.env:SAVE_DIR}/outputs/${project}/${job_name}/${now:%Y-%m-%d_%H-%M-%S}
save_every_since: 0
resume_path: null
pretrained_checkpoint: null
project: FlowPlannerTraining
job_name: flow_planner_npu
logger_level: info
seed: 3402

# NPU设备配置
device: npu
num_workers: 2
use_wandb: false
pin_mem: false

# 训练配置
train:
  batch_size: 512
  epoch: 5
  save_utd: 5

# 分布式训练配置
ddp:
  distributed: true
  world_size: ${oc.env:WORLD_SIZE}
  rank: ${oc.env:LOCAL_RANK}
  init_process_group: hccl
  addr: ${oc.env:MASTER_ADDR, localhost}
  port: ${oc.env:MASTER_PORT, 29529}

model_type: x_start

defaults:
  - model: flow_planner
  - core: flow_matching
  - data/dataset: nuplan_data
  - data/input_aug: input_aug
  - normalization_stats: waypoints_norm_stats
  - recorder: tensorboard
  - optimizer: adamw
  - scheduler: warmup_const
  - ema: ema
  - _self_

